#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network $syslog
# Required-Stop:     $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts aesdsocket
# Description:       Controls the aesdsocket service
### END INIT INFO

NAME="aesdsocket"
DAEMON="/usr/bin/$NAME"


# Load any environment variables or configuration
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

start() {
    echo "Starting $NAME..."
    start-stop-daemon -S -n $NAME -a $DAEMON -- -d
    if [ $? -eq 0 ]; then
        echo "$NAME started successfully."
    else
        echo "Failed to start $NAME."
    fi
}

stop() {
    echo "Stopping $NAME..."
    start-stop-daemon -K -n $NAME
    if [ $? -eq 0 ]; then
        echo "$NAME stopped successfully."
    else
        echo "Failed to stop $NAME."
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
